# Generated by Django 2.2.3 on 2019-07-26 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                ("modifiedon", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(blank=True, default="")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edit_access_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="_note_edit_access_to_+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "view_access_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="_note_view_access_to_+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
