# Generated by Django 2.2.3 on 2021-03-26 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20190726_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='edit_access_to',
            field=models.ManyToManyField(blank=True, related_name='edit_access_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='view_access_to',
            field=models.ManyToManyField(blank=True, related_name='view_access_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
